### ISSUE TITLE
咨询android studio 版本

### ISSUE THREAD

**Issue by enjoy-life-ing** [weikaizhi/AntiDebug#1]
你好！我下载了你的这个项目，但是在android studio 2.3.2上编译不通过。我想请教一下，你的这个项目是在android studio的什么版本上进行的开发？另外改项目是否可以正常编译通过？ 望大神不吝赐教，甚是感激。

**Comment by weikaizhi** [comment]
我用的Android Stuido3.3.2，AntiDebug/gradle/wrapper/gradle-wrapper.properties这个gradle的版本用的是4.6，你可以把这个版本改低点，另外工程根目录下的build.gradle的build tool也要改低点。

**Comment by name-cpu** [comment]
> 你好！我下载了你的这个项目，但是在android studio 2.3.2上编译不通过。我想请教一下，你的这个项目是在android studio的什么版本上进行的开发？另外改项目是否可以正常编译通过？ 望大神不吝赐教，甚是感激。

我用的Android Stuido3.3.2，AntiDebug/gradle/wrapper/gradle-wrapper.properties这个gradle的版本用的是4.6，你可以把这个版本改低点，另外工程根目录下的build.gradle的build tool也要改低点。
